-- คัดลอกโค้ดทั้งหมดนี้ไปวางใน SQL Editor ของ Supabase แล้วกดปุ่ม "Run"

-- 1. ตารางผู้ใช้งาน
CREATE TABLE IF NOT EXISTS public.users (
  id TEXT PRIMARY KEY,
  name TEXT,
  email TEXT UNIQUE,
  image TEXT,
  password TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ตารางการตั้งค่าแอป
CREATE TABLE IF NOT EXISTS public.settings (
  user_id TEXT DEFAULT 'global',
  key TEXT, 
  value TEXT,
  PRIMARY KEY(user_id, key)
);

-- 3. ตารางหมวดหมู่หลักสูตร
CREATE TABLE IF NOT EXISTS public.degree_categories (
  user_id TEXT DEFAULT 'global',
  id TEXT, 
  name TEXT NOT NULL, 
  required INTEGER NOT NULL,
  PRIMARY KEY(user_id, id)
);

-- 4. ตารางรายวิชาในแต่ละหมวดหมู่
CREATE TABLE IF NOT EXISTS public.degree_courses (
  user_id TEXT DEFAULT 'global',
  category_id TEXT, 
  course_code TEXT, 
  PRIMARY KEY(user_id, category_id, course_code)
);

-- 5. ตารางปฏิทินกิจกรรม
CREATE TABLE IF NOT EXISTS public.events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT DEFAULT 'global',
  title TEXT NOT NULL,
  startDate TEXT NOT NULL,
  endDate TEXT NOT NULL,
  type TEXT NOT NULL,
  region TEXT NOT NULL,
  dateStr TEXT NOT NULL,
  sendNotify BOOLEAN DEFAULT FALSE
);

-- 6. ตารางวิชาที่เรียนจบแล้ว
CREATE TABLE IF NOT EXISTS public.completed_courses (
  user_id TEXT DEFAULT 'global',
  course_code TEXT, 
  grade TEXT,
  PRIMARY KEY(user_id, course_code)
);

-- 7. ตารางฐานข้อมูลวิชาทั้งหมด (Master Data)
CREATE TABLE IF NOT EXISTS public.courses (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  credit INTEGER NOT NULL,
  day TEXT,
  time TEXT,
  room TEXT,
  examDate TEXT,
  examTime TEXT
);

-- 8. ตารางวิชาในตารางเรียนที่วางแผนไว้
CREATE TABLE IF NOT EXISTS public.planner_courses (
  user_id TEXT DEFAULT 'global',
  course_code TEXT,
  PRIMARY KEY(user_id, course_code)
);

-- ==========================================
-- ตั้งค่าสิทธิ์การเข้าถึง (Row Level Security)
-- ==========================================

-- เปิดการใช้งาน RLS
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.degree_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.degree_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.completed_courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.planner_courses ENABLE ROW LEVEL SECURITY;

-- สร้างนโยบายให้ทุกคนเข้าถึงได้ (สำหรับการเริ่มต้นใช้งานอย่างรวดเร็ว)
-- หมายเหตุ: ในระบบจริงควรตั้งค่าให้เฉพาะเจ้าของข้อมูล (user_id) เข้าถึงได้เท่านั้น
CREATE POLICY "Allow all access" ON public.users FOR ALL USING (true);
CREATE POLICY "Allow all access" ON public.settings FOR ALL USING (true);
CREATE POLICY "Allow all access" ON public.degree_categories FOR ALL USING (true);
CREATE POLICY "Allow all access" ON public.degree_courses FOR ALL USING (true);
CREATE POLICY "Allow all access" ON public.events FOR ALL USING (true);
CREATE POLICY "Allow all access" ON public.completed_courses FOR ALL USING (true);
CREATE POLICY "Allow all access" ON public.courses FOR ALL USING (true);
CREATE POLICY "Allow all access" ON public.planner_courses FOR ALL USING (true);
